### ISSUE TITLE
Urgent: Bug adding a user to some calendars

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#104]
Bug in Signe Laval: when I try to add a user, I cannot. I immediately get an error. See video.
This doesn't seem to be a problem in Tout Culture or DICI
It does happen in Artbi and in NAC Prod
Please check ALL calendars

https://github.com/user-attachments/assets/a811d6ba-4bd8-4fae-a999-44f12db612f8

**Comment by MaudeFJ** [comment]
It's still not working
@troughc

**Comment by AbhishekPAnil** [comment]
PR link to test :
https://github.com/culturecreates/footlight-app/pull/1467

**Comment by troughc** [comment]
Tested: PASSED

**Comment by troughc** [comment]
This looks like it was fixed in production. Is that correct? Thanks.

**Comment by AbhishekPAnil** [comment]
Yes the fix is updated in production.

**Comment by MaudeFJ** [comment]
Urgent
It's not working ! 
I dont have the error message but when I add new user and click save it's not in there I did it last week with theatretombeduciel.com and it wasn't there today and try again today and its not appearing in the list !!

**Comment by AbhishekPAnil** [comment]
I couldn't determine the exact cause, but I suspect it might be due to an invalid email, which prevented the invitation email from being sent initially. To address this, I’ve added email validation to the field. The email validation should prevent the form from being submitted if an invalid email is entered.
This is not a solution to the issue but rather a preventive measure for what I suspect might have happened while adding a user.
Please try adding the user again.

If the issue still exist, further investigation and additional details about the bug may be required.

**Comment by MaudeFJ** [comment]
Ah hahahha i think i did it wrong yesterday (like I put the website instead of the email) but I'm pretty positive I did it right last week.. but I did it again today and it worked ! thanks

**Comment by troughc** [comment]
Thank you for this @AbhishekPAnil
