### ISSUE TITLE
Festival des bieres de laval - cannot read property 'sort'

### ISSUE THREAD

**Issue by saumier** [culturecreates/tech-support-tickets#3]
De : Marilene Barale 
Envoyé : 29 mai 2023 13:44
À : Maude Fraser 
Objet : RE: Proposition
 
Salut Maude,
 
Je viens de tenter de compléter le formulaire, mais je recois une notification lorsque je veux l’enregistré et ca na fonctionne pas. Je ne pouvais pas non plus ajouté les artistes. Voir ci-dessous :

Merci!

![image002](https://github.com/culturecreates/tech-support-tickets/assets/419491/d2171ded-d04b-480b-ba35-157ad10d071c)

**Comment by saumier** [comment]
@AbhishekPAnil Can you please take a look at this screen grab and let me know if you have any ideas about this bug. Thx.

**Comment by AbhishekPAnil** [comment]
> Can you please take a look at this screen grab and let me know if you have any ideas about this bug. Thx.

@saumier 
From the above screen grab ,
the error is actually thrown from the backend .It would be helpful if we could get a screen grab of the network tab(api request) for the same.The error may be caused  due to any undefined property present in the  payload request from the  frontend.

**Comment by troughc** [comment]
@AbhishekPAnil unfortunately, we cannot find out what was in the event because Maude didn't create it - it was a contributor. I spoke with Gregory and the only clue is that 'sort' is in the message - why is it there and what kind of issue would it be indicating?

**Comment by troughc** [comment]
Abhishek and I worked on this a bit this morning. Some notes I took before doing some tests:

- there is no error in the front end. After the event is created and the save/send for review button is clicked, a request is sent to backend from front end. An error occurs because some key is getting undefined (which is unknown). 
We need to find out which property is getting undefined.
- Message “Something went wrong” from Front end
- Message “Cannot read property ‘sort’ of undefined” from back end.

With Abhishek, I created some events, both as an Admin and as a Guest. We used these sources for determining what data to put in the event details:
facebook event: https://www.facebook.com/events/540385391610776/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22page%22%7D]%7D&locale=fr_CA
https://www.festivaldesbieresdelaval.com/ - main page of main site
https://www.festivaldesbieresdelaval.com/programmation - main site with ticketing etc.

Each event we created in Production worked. We encountered no issue creating the events, saving the events, or sending for review. I deleted 2 of the events and kept one. Further testing is required to determine what is happening.
cc @saumier @SuhailAliyar @AbhishekPAnil

**Comment by saumier** [comment]
@AbhishekPAnil @troughc @dev-aravind Lets close this issue and implement logging for the backend. For the logging to help, it is critical to get the time that a bug occurs and add it to the tech support ticket.

**Comment by troughc** [comment]
> @AbhishekPAnil @troughc @dev-aravind Lets close this issue and implement logging for the backend. For the logging to help, it is critical to get the time that a bug occurs and add it to the tech support ticket.

Just waiting to hear back from the client first.

**Comment by troughc** [comment]
I didn't hear back from the client before her vacation so I will close.
