### ISSUE TITLE
Filter issue - some filters in the footlight cms (production) are not working

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#45]
Uploading Enregistrement d’écran, le 2023-12-11 à 08.25.32.mov…

**Comment by troughc** [comment]
@MaudeFJ can you please provide more details?

**Comment by MaudeFJ** [comment]
https://github.com/culturecreates/tech-support-tickets/assets/135066077/38cbc497-a352-4d0d-9147-6610bc4c1e6f

**Comment by MaudeFJ** [comment]
Sorry the video never upload the first time

**Comment by troughc** [comment]
@AbhishekPAnil the Publication filter is not working on the events Listing page. When you click it, nothing happens.

This is also true for the 'Class' filter on the Taxonomy page. Please double check other filters (they seem okay but please confirm).

**Comment by AbhishekPAnil** [comment]
Bug report:
The issue happened because of the change made in [819](https://github.com/culturecreates/footlight-app/issues/819).
An extra state variable was added to the dropdown component for [#819](https://github.com/culturecreates/footlight-app/issues/819.) which was getting undefined for other dropdowns.
I have added an independent state variable to the dropdown component as a hotfix and updated it in both staging and in production.

Closes tag added to the commit to [1a327ab](https://github.com/culturecreates/footlight-app/pull/861/commits/1a327abd8c1e8eebec87b8e3d45394bf3b6c6569)

**Comment by troughc** [comment]
Tested: PASSED

**Comment by troughc** [comment]
@MaudeFJ this issue is now fixed. Thanks!
