### ISSUE TITLE
Question + bugg

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#48]
When i'm selecting an artist from the arts data base, the event wont save... 
https://crclaval-my.sharepoint.com/:v:/g/personal/m_fraser_culturelaval_ca/EVOyP5wz3MJBm1z1pfE8SgsBazBOoZ312V_wlHsnB2ClBg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=6SxzQm 

Aussi ma question est : Est-ce qu'il est envisageable qu'il soit possible de bonifier directement les infos de arts data dans le CMS. 
Ayana ici est une artiste lavalloise qui n'est pas dans le répertoire de fooligth mais qui est dans arts data, mais dans arts data il n'y a pas de photo, ni de lien, ni d'ID que je peux connecter avec mon front end. 
Donc pour avoir l'affichage que je veux  comme ça :
<img width="697" alt="Capture d’écran, le 2024-01-26 à 15 41 30" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/30237503-dce7-4f12-9611-cb3ac083f382">
présentement il faudrait que crée une nouvelle fiche pour Ayana dans le répertoire. 
Merci

**Comment by troughc** [comment]
Bonjour-hi @MaudeFJ, 
I have created an issue for the bug of not being able to save an event after adding an artist from Artsdata - Good catch! This bug is a blocking bug so I put it at high priority.

Regarding your question, the short answer is Yes, you can provide enriching data to be reused in Artsdata.
 
We already have a process in the Footlight CMS that allows you to add enriching data to entities that already exist in Artsdata. 

In the "Ayana" example, you can use the Footlight CMS to add the missing (enriching) data, which is shared back to Artsdata because it is linked. This new data could then become available for community reuse. 

**The workflow in the Footlight CMS is as follows:**
1. You search for a person/org/place, for example Ayana. 
2. Ayana appears in 'Import from Artsdata'. select the entity to add it to your database. This entity is now linked to Artsdata.
3. Use the Edit Person screen (person details form) to add enriching data and save it. You can add the image, link to site etc., anything that you think is missing. This version of Ayana would have everything you need and it is linked to Artsdata. 
4. The steward for Artsdata can then review and approve your additions, and then make this new enriching data available in the main Arsdata entity according to their schedule. Quality control of validating any new information/enriching data that comes back to Artsdata from the community is managed on their end (by the person responsible for data upkeep in Artsdata.ca). Once they validate new data, it would be available for reuse.


@saumier did I miss anything important?

**Comment by MaudeFJ** [comment]
Hello,
Quand tu dis

  1.  You search for a person/org/place, for example Ayana.

On parle dans la case genre artiste, organisateur etc ?
Et j'imagine que c'est le bug qui m'empêche de pouvoir Éditer la fiche c'est ça ?  Parce que présentement il y a juste le nom et aucune autres options...
Merci



Maude Fraser

Responsable de Signé Laval  ​


450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3
  [cid:cd4679cb-ef47-4b25-b912-75aaa61c8a1e]

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Twitter<https://twitter.com/Signe_Laval>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.





________________________________
De : troughc ***@***.***>
Envoyé : 29 janvier 2024 12:24
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Question + bugg (Issue #48)


Bonjour-hi @MaudeFJ<https://github.com/MaudeFJ>,
I have created an issue for the bug of not being able to save an event after adding an artist from Artsdata - Good catch! This bug is a blocking bug so I put it at high priority.

Regarding your question, the short answer is Yes, you can provide enriching data to be reused in Artsdata.

We already have a process in the Footlight CMS that allows you to add enriching data to entities that already exist in Artsdata.

In the "Ayana" example, you can use the Footlight CMS to add the missing (enriching) data, which is shared back to Artsdata because it is linked. This new data could then become available for community reuse.

The workflow in the Footlight CMS is as follows:

  1.  You search for a person/org/place, for example Ayana.
  2.  Ayana appears in 'Import from Artsdata'. select the entity to add it to your database. This entity is now linked to Artsdata.
  3.  Use the Edit Person screen (person details form) to add enriching data and save it. You can add the image, link to site etc., anything that you think is missing. This version of Ayana would have everything you need and it is linked to Artsdata.
  4.  The steward for Artsdata can then review and approve your additions, and then make this new enriching data available in the main Arsdata entity according to their schedule. Quality control of validating any new information/enriching data that comes back to Artsdata from the community is managed on their end (by the person responsible for data upkeep in Artsdata.ca). Once they validate new data, it would be available for reuse.

@saumier<https://github.com/saumier> did I miss anything important?

**Comment by troughc** [comment]
> On parle dans la case genre artiste, organisateur etc ? Et j'imagine que c'est le bug qui m'empêche de pouvoir Éditer la fiche c'est ça ? Parce que présentement il y a juste le nom et aucune autres options...

@MaudeFJ Yes, I am talking about the field for performer, organizer or supporter in Event details.
And yes, it's not working for you right now because of the bug you found. Hence, I made it high priority to fix.

**Comment by troughc** [comment]
@saumier please review and provide any otaher missing information for Maude. Then we can close this issue.

**Comment by saumier** [comment]
@troughc Your description is good in theory. The specific details are a work in progress that needs to be reviewed by Frederic.

**Comment by troughc** [comment]
@MaudeFJ please see Gregory's comment. I am now closing this issue.
