### ISSUE TITLE
Bogue - the price from some co-motion events are not getting through

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#62]
Some events from the co-motion aggregator are not including all the ticket information. They appear to be events that were first added in the past - the examples we have were all created April 9 and updated yesterday (always by acomotion user).

https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66158de11406060064694c08
https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66158dec1406060064694e41
https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66158de81406060064694dd1

There were others but the price was manually added by the Admin.

**Comment by troughc** [comment]
@MaudeFJ can you provide an example of an event that is no t including the price? I checked ones that had not been updated by anyone other than the aggregator:

this event looks okay: https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66331fdb0796c300645a64f4

for this event: https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/6633997c0796c300645b1a17
There is no price, but when I looked at it, it says 0.00 dollars (when you follow the buy online link)


this event looks okay: https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/6629e77f0796c3006456d0d0


I loked at this event: https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/6629e78c0796c3006456d2c8
There is a buy link and no price, but I think that is because the event is full (complet)?

**Comment by MaudeFJ** [comment]
Salut here's an exemple : https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66158de11406060064694c08

**Comment by MaudeFJ** [comment]
https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66158dec1406060064694e41
https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66158de81406060064694dd1

**Comment by troughc** [comment]
Thanks @MaudeFJ . Looks like all three of these were created April 9 and updated yesterday. I will assign this to the team to investigate.

**Comment by MaudeFJ** [comment]
There were more but I added prices manually.
Do you need those one to stay like that or can I update them manually for publishing ?


Maude Fraser

Responsable de Signé Laval  ​


450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.

________________________________
De : troughc ***@***.***>
Envoyé : Friday, May 3, 2024 8:48:00 AM
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Bogue - the price from the co-motion event are not getting tru (Issue #62)


Thanks @MaudeFJ<https://github.com/MaudeFJ> . Looks like all three of these were created April 9 and updated yesterday. I will assign this to the team to investigate.

**Comment by troughc** [comment]
@MaudeFJ I don't need anything else from you. Thanks!

**Comment by troughc** [comment]
@sahalali please look into this to see if you can locate where the issue lies.

I did some back tracking with this event: 
https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66158de81406060064694dd1
https://www.co-motion.ca/spectacles/anthony-kavanagh-happy/ 

The event comes from the console. Here it is in Artsdata: https://kg.artsdata.ca/entity?uri=http%3A%2F%2Fkg.footlight.io%2Fresource%2Fco-motion-ca_anthony-kavanagh-happy
The ticket prices are accessible in the offer section.

**Comment by troughc** [comment]
> There were more but I added prices manually. Do you need those one to stay like that or can I update them manually for publishing ?

@MaudeFJ sorry, I misread your message. Could you please leave them as is for now so we can test.

**Comment by saumier** [comment]
@troughc Is this still an open issue with Maude?

**Comment by troughc** [comment]
To my knowledge, this has not been investigated.

**Comment by saumier** [comment]
@dev-aravind This is another issue that we need to get back to the client on. Please investigate as it could reveal some system bugs or data mapping bugs. Thx. Please report back after doing some initial investigation as I want to get the ball rolling.

**Comment by dev-aravind** [comment]
@troughc The issue does not appear to be present in the current version of Aggregator. The offers were loaded perfectly during my test runs. If this issue pops up again we can take a look. Let me know if you have any questions.

**Comment by troughc** [comment]
Thanks. @MaudeFJ this issue should be resolved. Please let me know if it happens again.
