### ISSUE TITLE
Long image name preventing from editing 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#64]
https://github.com/culturecreates/tech-support-tickets/assets/135066077/a46035f7-a749-405a-8239-d1d59ffda7c0

I can't edit the shape of the image when the image name is really long.

**Comment by troughc** [comment]
@AbhishekPAnil this issue is related to name length of images.  Maude already shortened the name of the image for this example event here: https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/66476dc79f43170063fb4b81
Expected behaviour: image name should wrap so that the edit button fits inside the UI component.

**Comment by SyamBabu-M** [comment]
@troughc this can be tested [here](https://pr-1139.dla06mbe0wyl7.amplifyapp.com/). This is the same PR for [#1114](https://github.com/culturecreates/footlight-app/issues/1114).

**Comment by troughc** [comment]
Name doesn't wrap to two lines, instead you get ...
But this is an acceptable solution.: PASSED
