### ISSUE TITLE
Idea : being able to pull biography of artist to fill in if there is no Event description

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#67]
As more info on artists is gonna be available being able to use it in different box would be nice

**Comment by troughc** [comment]
@MaudeFJ why can't you use the Description field?

**Comment by MaudeFJ** [comment]
I mean, in the description field, if there is no description, like evenko they don't put a description, I could use arts data info and pull a biography of the artist connected to the event if there is one, in place of the nonexistant description.

**Comment by troughc** [comment]
I see. but I think that when you import events, the information about an artist that is available in Artsdata is being pulled in (if there is a link to artsdata). Are you not already getting performer info from Artsdata? Or do you mean that you are manually adding evenko events?

**Comment by MaudeFJ** [comment]
Evenko is a fictional exemple. 
If there is info about the artiste it's getting in as the description of the artistes. I would like the cms to offer me to use that description as the description of the event.

**Comment by troughc** [comment]
Okay I understand. I'm not sure...
From a data point of view, using bios for event descriptions is problematic. An artist bio is not the same thing as an event description. Thus, it would often not be great quality / not inform people about the event.

So, let's go through it: you want to use an artist bio (person description) as the description for the event. 
On this site, the artist description is listed on bio (not event description):
https://bradleyertaskiran.com/en/artists/mathieu-beausejour-en/#bio

This works - displaying the performer bio on your page under the right title (biography).

Here is another example of a bio - it's very long and doesn't describe any specific ballet show:
**Les Grands Ballets Canadiens:**
Les Grands Ballets Canadiens de Montréal was founded in 1957 by [Ludmilla Chiriaeff](https://en.wikipedia.org/wiki/Ludmilla_Chiriaeff). Conductor and composer [Michel Perrault](https://en.wikipedia.org/wiki/Michel_Perrault) served as the organization’s first music director.
Since its creation, Les Grands Ballets has performed a broad range of dance, ranging from classics to major contemporary work. Under the direction of Chiriaeff and [Fernand Nault](https://en.wikipedia.org/wiki/Fernand_Nault) (1965–1973), [Brian Macdonald](https://en.wikipedia.org/wiki/Brian_Macdonald_(choreographer)) (1974–1977) and Lawrence Rhodes (1990–1999), the institution fostered the development of such notable artists as [James Kudelka](https://en.wikipedia.org/wiki/James_Kudelka), [Édouard Lock](https://en.wikipedia.org/wiki/%C3%89douard_Lock) and [Ginette Laurin](https://en.wikipedia.org/wiki/Ginette_Laurin).
In 1981 the company participated alongside the [National Ballet of Canada](https://en.wikipedia.org/wiki/National_Ballet_of_Canada), the [Royal Winnipeg Ballet](https://en.wikipedia.org/wiki/Royal_Winnipeg_Ballet), le Groupe de la Place Royale, the Danny Grossman Dance Company, the [Toronto Dance Theatre](https://en.wikipedia.org/wiki/Toronto_Dance_Theatre), Winnipeg Contemporary Dancers and the Anna Wyman Dance Theatre in the Canadian Dance Spectacular,[[1]](https://en.wikipedia.org/wiki/Les_Grands_Ballets_Canadiens#cite_note-1) a dance show at Ottawa’s [National Arts Centre](https://en.wikipedia.org/wiki/National_Arts_Centre) which was filmed by the [National Film Board of Canada](https://en.wikipedia.org/wiki/National_Film_Board_of_Canada) for the 1982 documentary film [Gala](https://en.wikipedia.org/wiki/Gala_(1982_film)).[[2]](https://en.wikipedia.org/wiki/Les_Grands_Ballets_Canadiens#cite_note-2)
In 2000, Gradimir Pankov became artistic director. A native of Macedonia, Pankov previously served as artistic director of [Nederlands Dans Theater](https://en.wikipedia.org/wiki/Nederlands_Dans_Theater) II (Netherlands), the National Ballet of Finland (Helsinki), the [Cullberg Ballet](https://en.wikipedia.org/wiki/Cullberg_Ballet) (Sweden), and Ballet du [Grand Théâtre de Genève](https://en.wikipedia.org/wiki/Grand_Th%C3%A9%C3%A2tre_de_Gen%C3%A8ve) (Switzerland).
In 2017, Ivan Cavallari became the artistic director of les Grands Ballets. Born in Italy, he trained at Teatro alla Scala Ballet School in Milan. Before becoming artistic director of les Grands Ballets, he was artistic director of the West Australian Ballet and then the [Ballet de l'Opéra national du Rhin](https://en.wikipedia.org/wiki/Ballet_de_l%27Op%C3%A9ra_national_du_Rhin). The ballet masters are Hervé Courtain, appointed in 2017, and Marina Villanueva Arias, appointed in 2020.[[3]](https://en.wikipedia.org/wiki/Les_Grands_Ballets_Canadiens#cite_note-3)
The company has commissioned work from some of the world’s most prominent choreographers: The Queen of Spades by Kim Brandstrup; The Butterfly Effect by Shawn Hounsell; Between Ashes and Angels by Adam Hougland; Noces, Cinderella and The Rite of Spring by [Stijn Celis](https://en.wikipedia.org/wiki/Stijn_Celis); The Little Prince, Possibly Six and TooT by [Didy Veldman](https://en.wikipedia.org/wiki/Didy_Veldman); The Beast and the Beauty by Kader Belarbi; Four Seasons by [Mauro Bigonzetti](https://en.wikipedia.org/wiki/Mauro_Bigonzetti); Minus One and Danz by [Ohad Naharin](https://en.wikipedia.org/wiki/Ohad_Naharin); Rodin/Claudel by [Peter Quanz](https://en.wikipedia.org/wiki/Peter_Quanz); and Re–II by [Shen Wei](https://en.wikipedia.org/wiki/Shen_Wei).
Its repertoire also includes major acquisitions by such artists as [Mats Ek](https://en.wikipedia.org/wiki/Mats_Ek), [Jiří Kylián](https://en.wikipedia.org/wiki/Ji%C5%99%C3%AD_Kyli%C3%A1n), [Jean-Christophe Maillot](https://en.wikipedia.org/wiki/Jean-Christophe_Maillot) and [Christopher Wheeldon](https://en.wikipedia.org/wiki/Christopher_Wheeldon), along with works by young creators like Stephan Thoss, Didy Veldman and Peter Quanz. In 2008 Gradimir Pankov established the national choreographic contest, won by Jean-Sébastien Couture, which has allowed Les Grands Ballets to showcase work by emerging Canadian choreographers. Each season, Les Grands Ballets invited international companies to perform as part of its program; the list includes Houston Ballet, Royal Winnipeg Ballet, Alvin Ailey® American Dance Theater, Cullberg Ballet (Sweden), Compañía Nacional de Danza (Spain), Warsaw Ballet (Poland), Cloud Gate Dance Theatre (Taiwan), Shen Wei Dance Arts (New York City), Ballet de l’Opéra de Lyon (France), Dutch National Ballet and Eifman Ballet Theatre of St-Petersburg (Russia).
Since Ivan Cavallari took artistic leadership, the company focuses on extending its repertoire to both showcase the great ballet classics and acquire new works by emerging contemporary creators.

**Comment by troughc** [comment]
What problem are you trying to solve? An empty event description? An empty-looking page?

**Comment by MaudeFJ** [comment]
Yes empty event description where i need to invent stuff.
So having a Mathieu Beausejour bio is better than having to find a description for the event and maybe translate it.


Maude Fraser

Responsable de Signé Laval  ​


450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3
  [cid:00a2b607-c0ca-4f1f-b986-ecf667be6997]

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Twitter<https://twitter.com/Signe_Laval>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.





________________________________
De : troughc ***@***.***>
Envoyé : 5 juin 2024 12:48
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Assign ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Idea : being able to pull biography of artist to fill in if there is no Event description (Issue #67)


What problem are you trying to solve? An empty event description?

**Comment by troughc** [comment]
Okay, there is a solution for you today. You can easily access existing artists descriptions from an event.
After an artist (performer) has been saved to your CMS, (with an aggregated event or explicitly by a person), you can easily access it's data and copy a description (if there is one) to your event 

Steps to copy descriptions:

1. Open the event. 
2. Go to the performer field to access the performer that is already displayed there (or add a performer that is already in your CMS database). 
**NOTE:** If you need to add the performer from Artsdata, add it, save the event and reopen the event before continuing. 
3. In the Performer component, click the "Èditer" button. This opens the people/organization that is linked to the event.
4. If there is a description available, copy it.
5. Click "Retour a l'écran précédent" at the top of the page to go back to the event.
6. Paste and modify the description and then save.
