### ISSUE TITLE
"Langue de l'événement" disapear when clicking

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#78]
[Enregistrement d’écran, le 2024-08-01 à 11.48.47.zip](https://github.com/user-attachments/files/16458932/Enregistrement.d.ecran.le.2024-08-01.a.11.48.47.zip)

Additional notes and observations from Caitlin:
When you click Event Language, it is removed from the blue text on the left but doesn't get added as a field in the main form.
I tested in staging (in English and French UIs); confirmed this bug exists in MOST calendars. 
- ONLY Tout Culture and ArtsCultureNB do NOT have the bug. 
- When the Event language in those calendars, it appears as expected. These are bilingual calendars; however other bilingual calendars do have the bug. 

When debugging this issue, please confirm that all blue text items in all forms are functioning as expected. Thanks!

**Comment by AbhishekPAnil** [comment]
Bug Report:
Calendars that haven't created an inLanguage taxonomy couldn't see the "language of event" field in the event form. Since Tout culture and ArtscultureNB had already created the inLanguage taxonomy, they could see this field.

If a calendar has not created the inLanguage taxonomy, it shouldn't show in the "add more fields" section (blue text items). I have fixed this issue. Now, calendars that haven't created the inLanguage taxonomy won't be able to view it in the "add more fields" section. Once the taxonomy is created, they will be able to see it.

**Comment by troughc** [comment]
Hi @MaudeFJ 
As Abhishek explained, the in language option should only appear when you have created a taxonomy for this Standard field. Once you create the taxonomy, the option should appear in the Event form. 
The bug was that the option was displayed (as blue text) when there was no taxonomy (no options) for it. This is now fixed. In your calendar the option is not available yet (you need to create the taxonomy).
To create the taxonomy, add + taxonomy and then select it in the dropdown shown here :


![Image](https://github.com/user-attachments/assets/edb904b1-47f9-4a58-ad9d-1986eada94cd)

Then add your languages and save.

IMPORTANT: You do NOT need to create the Discipline taxonomy shown in the screenshot - this is a new feature that you can ignore as your webteam has already configured your website according to your current settings. If you have questions, I am available.
