### ISSUE TITLE
Other prob with picture 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#90]
Some time, person or group dont have their pictures displayed in the event, yet they do have a picture... 
<img width="650" alt="Capture d’écran, le 2024-09-23 à 11 32 41" src="https://github.com/user-attachments/assets/eeafb0d8-e92b-48db-bd84-e66d65a5f5a8">
<img width="693" alt="Capture d’écran, le 2024-09-23 à 11 32 47" src="https://github.com/user-attachments/assets/6b87d1fe-87b7-4f68-a497-4526407921f4">

**Comment by troughc** [comment]
@MaudeFJ the reason the organization's picture is not displayed in the event page component is because that component would display a LOGO image, not an IMAGE image. 

For people, on the other hand, it should display the headshot image. We will look into adding this.

Additionally, I did notice that, for the particular organization you referenced, the image is also not displayed on the read only page for this group (Emilis). I will look into this as well

**Comment by troughc** [comment]
@MaudeFJ I have created a separate enhancement request to use a **Person's** (main) image as an identifying image (like a logo) so that this image is displayed if you select a person as a performer for an event.

As for an **Organization** image - we don't display the image that has been added for an organization in the Events view because the Organization logo is used. 
That said, the image is included in the data, so you can use it on your website if that is what you want to do.

I have also created a separate issue that you uncovered for me - to add the image field to the read-only page of organizations.

**Comment by MaudeFJ** [comment]
thanks !
________________________________
De : troughc ***@***.***>
Envoyé : 23 septembre 2024 14:52
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Other prob with picture (Issue #90)


@MaudeFJ<https://github.com/MaudeFJ> I have created a separate enhancement request to use a Person's (main) image as an identifying image (like a logo) so that this image is displayed if you select a person as a performer for an event.

As for an Organization image - we don't display the image that has been added for an organization in the Events view because the Organization logo is used.
That said, the image is included in the data, so you can use it on your website if that is what you want to do.

I have also created a separate issue that you uncovered for me - to add the image field to the read-only page of organizations.

**Comment by troughc** [comment]
@MaudeFJ this is now fixed; you can see the picture of an artist in the event when you select it. 
See screenshot.
I am closing the issue.
<img width="1208" alt="Screenshot 2024-11-27 at 3 02 47 PM" src="https://github.com/user-attachments/assets/65a901d5-812d-40f6-9f64-b8cddaa6cbb0">
