### ISSUE TITLE
No inlangage in schema

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#92]
@sahalali @AbhishekPAnil this request is to configure the Signe Laval calendar Events to automatically set the in language taxonomy to French and have it be displayed in the Event form. 

**Details:**
Signe Laval would like all events to be **automatically** set to French language. 
To do this going forward, all new events in the Signe Laval event form should always display the in Language field in the event form and French should be prefilled. 
Then the user can edit and do two things:
- add additional langauges that are listed in the taxonomomy as they need (for example, they can add spanish, english etc)
- remove french if they want.

**Additional request:** For ALL existing events, add French to in language field, do not overwrite other languages if they are already selected.

Request from Maude, our client:
_Hello, i realized that the in langage  is not there when I validate the events in my calendar :
https://validator.schema.org/#url=https%3A%2F%2Fsignelaval.com%2Ffr%2Fevenements%2F66da98c8345131006449a596%2Fheure-du-conte-bilingue-francais-espagnol
https://schema.org/inLanguage
Is it possible to just put french for all event and put the other language that is selected with the language taxonomies I created ? 
This is not urgent, but I'm just putting it here! thanks_

**Comment by troughc** [comment]
@MaudeFJ, hmm, to add French as the language of all your events, you would probably first need to have it in your "in language" taxonomy. Then, you could apply it to all your events. 
@saumier, what do you think?, is that right? 
If I understand Maude correctly, she would like of the language of all her events to automatically be set to French. My thought was, French has to be part of the in language taxonomy, before we could even do this as a special configuration (automatically adding a property that denotes french as the language of all events.
In language property/field would then always be displayed in the UI for, at minimum, the Admin (by restricting the view).

**Comment by saumier** [comment]
@troughc Yes, the taxonomy for 'inLanguage' should have French.  I looked and there is French in the taxonomy for inLanguage on Signé Laval.

**Comment by MaudeFJ** [comment]
Yes i added it in between your exchanges

________________________________
De : Gregory Saumier-Finch ***@***.***>
Envoyé : 29 septembre 2024 22:25
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] No inlangage in schema (Issue #92)


@troughc<https://github.com/troughc> Yes, the taxonomy for 'inLanguage' should have French. I looked and there is French in the taxonomy for inLanguage on Signé Laval.

**Comment by troughc** [comment]
@MaudeFJ @saumier can you please review the description at the top? (first comment). Let me know if there are any issues. thanks.

**Comment by saumier** [comment]
@troughc Here is my feedback

> Signe Laval would like all events to be automatically set to French language.

This sounds like a new feature to be added to CMS. The new feature would allow the admin to select a default for a taxonomy. 

For manual data entry: if the taxonomy is configured in the calendar settings to be mandatory, and there is a default value set in the Taxonomy, then it should be pre-filled.
For aggregating events:  if the taxonomy is configured in the calendar settings to be mandatory, and there is a default value set in the Taxonomy, then if the field is empty it should be set to the default.

> Additional request. For ALL existing events, add French to in language field, do not overwrite other languages if they are already selected.

This can be done with the bulk download and upload.

**Comment by AbhishekPAnil** [comment]
Frontend tasks : 1h
1.For unilingual calendars ,prefill new events with inLanguage taxonomy with the respective content language ,if it exists .

**Comment by suhail-aliyar** [comment]
@AbhishekPAnil The above solution will make the events fragile and will be hard to implement.

Proposed solution:

1. We need to add a new configuration to the calendars to set the default inLanguage. This option should be available on the calendar settings page, allowing users to select a taxonomy and a default concept from the taxonomy.

In the future, it would be helpful to have an option to directly map the taxonomy to a Schema.org class or property. For example, mapping a taxonomy with https://schema.org/inLanguage.

How is this useful? In this case, the user won't have to select a taxonomy first and then the concept. Instead, they can select concepts from a taxonomy mapped to https://schema.org/inLanguage.
2. When a user creates/updates events without an inLanguage, add the default concept to the event.

Note: Currently, we can also start with just making changes in backed alone.

Estimation: 8 hours (backend)
@AbhishekPAnil Can you estimate the front end effort?

**Comment by AbhishekPAnil** [comment]
Frontend tasks modified: 11h
1.Add the field to select default  inLangage in calendar settings page.
2.Api integration for getting inLangage taxonomy.
3.Prefill new events with the default inlanguage taxonomy.
4.Api integration for saving the inLanguage in calendar settings

**Comment by troughc** [comment]
Caitlin and Suhail to discuss Tuesday. Caitlin to review comment

**Comment by troughc** [comment]
Plan: 
1. make a custom change in the BE to configure this for Signe Laval (set French to be the default language of the event for every new event created, including those imported by aggregators)
2. make a chnage in the FE to display the language of the event as French right from the beginning (creation step).
3. Apply a migration script to add the default value (French in language) for existing events that do NOT already have a 'language of the event' concept applied.

Estimate is 6-8 hours

**Comment by troughc** [comment]
@sahalali test results in production against these expected results:
1. make a custom change in the BE to configure this for Signe Laval (set French to be the default language of the event for every new event created, including those imported by aggregators)
2. make a change in the FE to display the language of the event as French right from the beginning (creation step).
3. Apply a migration script to add the default value (French in language) for existing events that do NOT already have a 'language of the event' concept applied.

1. Signe Laval seems to be configured in the BE to set french as the default language: **PASSED**
2. When I create a new event in production, the default language is set to french: **PASSED**
3. Apply a migration script to add the default value (French in language) for existing events that do NOT already have a 'language of the event' concept applied. **This does not seem to be implemented**

Question: I cannot confirm that new events coming from aggregators are getting the default language tag because the most recent date an event was created from an aggregator is October 4. **Can you please confirm that aggregator events are being set to French by default?**

**Comment by troughc** [comment]
Regarding my question above: 
_Question: I cannot confirm that new events coming from aggregators are getting the default language tag because the most recent date an event was created from an aggregator is October 4. Can you please confirm that aggregator events are being set to French by default?_

I saw that the new events that came in from Ville Laval had the French language tag, so that is working well from what I can tell. :)

**Comment by suhail-aliyar** [comment]
Migrated all existing Signe-Laval events that did not have a specified language to French.

**Comment by troughc** [comment]
Thank you team. PASSED!
I am closing this issue.
